// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5aogq6jpANvRfZVcqk3ovM
// Component: OtWiZezfP5Zh
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Button from "../../Button"; // plasmic-import: iD4oiPqdGNb9/component
import { useScreenVariants as useScreenVariantsjAuPUjXUwo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jAu_PUj_xUwo/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 5aogq6jpANvRfZVcqk3ovM/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: OtWiZezfP5Zh/css
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: YuAb_P8XrcXQ/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: ZGeebJCm7gFd/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjAuPUjXUwo()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"navigateBar"}
            data-plasmic-override={overrides.navigateBar}
            className={classNames(projectcss.all, sty.navigateBar)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___5BG1)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__d3JUa)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mwIIh)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"82px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/instant_capture_launching_page/images/beigeAndBlackMinimalistSkincareLogopng.png",
                    fullWidth: 500,
                    fullHeight: 500,
                    aspectRatio: undefined
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___16Qx)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__ukd0)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__btoCv)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__mo7Ib)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xsRz9
                      )}
                    >
                      {"Services"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__hvrkE)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___5Qzv9)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__xal29)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dAjcB
                      )}
                    >
                      {"Features"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__gqSIt)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__y7DZt)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg___3Lln5)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___42KOa
                      )}
                    >
                      {"Company"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__peyG)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___45Y8)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__s8G8K)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nhuW5
                      )}
                    >
                      {"Contact"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__x9Bdv)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__aXjGy)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__zdRpn)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sMusJ
                      )}
                    >
                      {"Log in"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__iZ4YN)}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__sjt8)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__qhxud)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vfXt0
                      )}
                    >
                      {"Sign up"}
                    </div>
                  </Button>
                </Stack__>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hZce9)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button___5S74
                      )}
                    >
                      {"Sign up"}
                    </button>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__fMejE
                      )}
                      color={"clear"}
                      endIcon={
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__xH6)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__xipKr)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ad786
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button>
                  </div>
                ) : null}
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h2
                    data-plasmic-name={"textH2"}
                    data-plasmic-override={overrides.textH2}
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.textH2
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#8D8EE2", fontStyle: "italic" }}
                      >
                        {"Instant Capture"}
                      </span>
                      <React.Fragment>
                        {
                          " is an real-time AI productivity notes taking tool with open-source templates. "
                        }
                      </React.Fragment>
                    </React.Fragment>
                  </h2>
                }

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </h1>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kb5C
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__eSyRt
                    )}
                  >
                    {
                      "We ignited the unprecedented journey for worldwide students and learners to access free knowledge bases with high credibility"
                    }
                  </h4>
                }

                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            <Button className={classNames("__wab_instance", sty.button__ocraJ)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wRNpz
                )}
              >
                {"LEARN MORE"}
              </div>
            </Button>
            <PlasmicImg__
              data-plasmic-name={"launchImg"}
              data-plasmic-override={overrides.launchImg}
              alt={""}
              className={classNames(sty.launchImg)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"1000px"}
              displayMinHeight={"0"}
              displayMinWidth={"500px"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/instant_capture_launching_page/images/blueModernMobileApplicationPresentation1Png.png",
                fullWidth: 1920,
                fullHeight: 1080,
                aspectRatio: undefined
              }}
            />

            <section
              data-plasmic-name={"features"}
              data-plasmic-override={overrides.features}
              className={classNames(projectcss.all, sty.features)}
            >
              <div className={classNames(projectcss.all, sty.columns__cdsKf)}>
                <div className={classNames(projectcss.all, sty.column__lSr7)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kSqe5)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"35.97%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/instant_capture_launching_page/images/image2.png",
                      fullWidth: 375,
                      fullHeight: 368,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Gviq
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__i9FYy
                          )}
                        >
                          {"Multi-source imports within seconds"}
                        </h4>
                      }

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__nyYrd)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__iWcyo)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"35.97%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/instant_capture_launching_page/images/image3.png",
                      fullWidth: 226,
                      fullHeight: 223,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ewL5G
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__ldI1L
                          )}
                        >
                          {"Auto-building system & structure"}
                        </h4>
                      }

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__mjmK5)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mr561)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"39.46%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/instant_capture_launching_page/images/image4.png",
                      fullWidth: 253,
                      fullHeight: 231,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rWlXe
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__rNiU
                          )}
                        >
                          {"Export as Flashcards, Quizzes, Notes"}
                        </h4>
                      }

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.columns___4IImw)}>
                <div className={classNames(projectcss.all, sty.column___7DPsV)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ly3DV)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"46.36%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/instant_capture_launching_page/images/image5.png",
                      fullWidth: 249,
                      fullHeight: 204,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zkGwa
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__dhSU
                          )}
                        >
                          {"Instant Access to Websearch"}
                        </h4>
                      }

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__vBUh)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__riClj)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"35.97%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/instant_capture_launching_page/images/image6.png",
                      fullWidth: 247,
                      fullHeight: 235,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eu1Df
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4___0RsQr
                          )}
                        >
                          {"Free Templates & Knowledge Bases"}
                        </h4>
                      }

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__pRxoN)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cDwvY)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"39.46%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/instant_capture_launching_page/images/image8.png",
                      fullWidth: 226,
                      fullHeight: 206,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tAbVx
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4___0Xvxv
                          )}
                        >
                          {"Your Personal StudyChatbot"}
                        </h4>
                      }

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
              </div>
            </section>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigateBar",
    "section",
    "h1",
    "textH2",
    "launchImg",
    "features"
  ],

  navigateBar: ["navigateBar"],
  section: ["section", "h1", "textH2", "launchImg", "features"],
  h1: ["h1", "textH2"],
  textH2: ["textH2"],
  launchImg: ["launchImg"],
  features: ["features"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigateBar: makeNodeComponent("navigateBar"),
    section: makeNodeComponent("section"),
    h1: makeNodeComponent("h1"),
    textH2: makeNodeComponent("textH2"),
    launchImg: makeNodeComponent("launchImg"),
    features: makeNodeComponent("features"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
